<a href="https://colab.research.google.com/github/leejunho12316/HonGongMachine/blob/main/Udemy_linalg_Matrix_Rank.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

#행렬 rank 확인

In [6]:
A = np.array(([1,2],[1,1]))
print("일반적인 행렬 A의 rank")
print("rank(A) = ", np.linalg.matrix_rank(A))

일반적인 행렬 A의 rank
rank(A) =  2


In [7]:
A = np.array([[1, 1.0000001], [1,1]])
print("거의 선형 종속적인 행렬 A의 rank")
print("rank(A) = ", np.linalg.matrix_rank(A))

거의 선형 종속적인 행렬 A의 rank
rank(A) =  2


In [12]:
A = np.array([[1,2],[1,1]])
U, S, VT = np.linalg.svd(A)
print("SVD 행렬 분해")
print("U = ", U)
print("S = ", S, "(0이 아닌 값이 2개이므로 rank가 2)")
print("VT = ", VT)

SVD 행렬 분해
U =  [[-0.85065081 -0.52573111]
 [-0.52573111  0.85065081]]
S =  [2.61803399 0.38196601] (0이 아닌 값이 2개이므로 rank가 2)
VT =  [[-0.52573111 -0.85065081]
 [ 0.85065081 -0.52573111]]


In [16]:
A = np.array([[1,2],[2,4]])
U, S, VT = np.linalg.svd(A)
print("U = ", U)
print("S = ", S, "(1.98602732e-16는 거의 0이 이므로 rank가 1)")
print("VT = ", VT)

U =  [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]
S =  [5.00000000e+00 1.98602732e-16] (1.98602732e-16는 거의 0이 이므로 rank가 1)
VT =  [[-0.4472136  -0.89442719]
 [-0.89442719  0.4472136 ]]


#행렬 분해

In [28]:
L = np.array([[1,0],[2,1]])
A = L @ L.T

print("---Cholesky 행렬분해---")
print("L x LT = ", A)
print("L = ", np.linalg.cholesky(A))

---Cholesky 행렬분해---
L x LT =  [[1 2]
 [2 5]]
L =  [[1. 0.]
 [2. 1.]]


In [29]:
import scipy
A = np.array(([1,2,3],[3,4,5],[5,6,7]))
print("---LU  행렬분해---")
P, L, U = scipy.linalg.lu(A)
print("P = (P는 Permutation 행렬로 L 의 행을 재배치하는데 쓰임)\n",P)
print("L = \n",L)
print("U = \n",U)

---LU  행렬분해---
P = (P는 Permutation 행렬로 L 재배치하는데 쓰임)
 [[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
L = 
 [[1.  0.  0. ]
 [0.2 1.  0. ]
 [0.6 0.5 1. ]]
U = 
 [[5.  6.  7. ]
 [0.  0.8 1.6]
 [0.  0.  0. ]]


In [34]:
A = np.array([[1,2],[3,4],[5,6]])
Q, R = np.linalg.qr(A)
Q
print("Q = \n",Q)
print("R = \n", R)

Q = 
 [[-0.16903085  0.89708523]
 [-0.50709255  0.27602622]
 [-0.84515425 -0.34503278]]
R = 
 [[-5.91607978 -7.43735744]
 [ 0.          0.82807867]]


In [38]:
print("3x2 Q가 어떻게 직교행렬인가?")
print("Q.T @ Q = I 나옴. (Q @ Q.T는 안나옴)")
print(Q.T @ Q)

3x2 Q가 어떻게 직교행렬인가?
Q.T @ Q = I 나옴. (Q @ Q.T는 안나옴)
[[1.00000000e+00 6.18439648e-17]
 [6.18439648e-17 1.00000000e+00]]


#Forbenius Norm and Trace

In [50]:
A = np.array([[1,2],[3,4],[5,6]])
print("Forbenius Norm = 모든 원소 제곱해서 더한거 루트")
print("np.linalg.norm(A) = ", np.linalg.norm(A))
print("np.sqrt = ", np.sqrt(1+4+9+16+25+36))

print("대각곱 공식 : ")
print(np.sqrt(np.trace(A @ A.T)))
print(np.sqrt(np.trace(A.T @ A)))

Forbenius Norm = 모든 원소 제곱해서 더한거 루트
np.linalg.norm(A) =  9.539392014169456
np.sqrt =  9.539392014169456
대각곱 공식 : 
9.539392014169456
9.539392014169456


#SVD (Singular Value Decomposition)

In [65]:
A = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
U, S, VT = np.linalg.svd(A)

In [66]:
U

array([[-0.18923073, -0.81497959,  0.37684105, -0.39748059],
       [-0.36846753, -0.40525508, -0.2061902 ,  0.81085486],
       [-0.54770432,  0.00446943, -0.71814276, -0.42926795],
       [-0.72694112,  0.41419393,  0.54749191,  0.01589368]])

In [67]:
S

array([1.91491774e+01, 1.14411715e+00, 1.08189867e-15])

In [68]:
VT

array([[-0.47635167, -0.57203953, -0.66772738],
       [ 0.77873129,  0.07812881, -0.62247367],
       [-0.40824829,  0.81649658, -0.40824829]])

In [62]:
print("U가 직교행렬인지 확인")
Z = U @ U.T
print("Z = \n", Z)
I = np.eye(len(Z))
print("I = \n", I)

print("***allclose? = ", np.allclose(Z, I),"***")

U가 직교행렬인지 확인
Z = 
 [[ 1.00000000e+00 -1.49623437e-16  9.19305943e-17  2.76029300e-16]
 [-1.49623437e-16  1.00000000e+00  2.76362030e-17  1.54733747e-16]
 [ 9.19305943e-17  2.76362030e-17  1.00000000e+00 -3.56629509e-17]
 [ 2.76029300e-16  1.54733747e-16 -3.56629509e-17  1.00000000e+00]]
I = 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
***allclose? =  True ***


In [69]:
print("VT가 직교행렬인지 확인")
Z = VT @ VT.T
print(Z)
I = np.eye(len(Z))
print(I)
print("***allclose? = ", print(np.allclose(Z,I)))

VT가 직교행렬인지 확인
[[ 1.00000000e+00  2.92372402e-18 -2.10291059e-16]
 [ 2.92372402e-18  1.00000000e+00 -2.20293883e-17]
 [-2.10291059e-16 -2.20293883e-17  1.00000000e+00]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
True
***allclose? =  None


In [80]:
#A@AT AT@A가 거의 특이행렬이라는 것을 확인
print("rank(AT @ A) = ", np.linalg.matrix_rank(A.T @ A),"\n",
      "S의 0이 아닌 값의 개수 = 2\n",
      "-> 특이행렬")

rank(AT @ A) =  2 
 S의 0이 아닌 값의 개수 = 2
 -> 특이행렬


또 다른 SVD 표현방법
$$
USV^T = \sum_{i=1}^r \sigma_i \, \mathbf{u}_i \mathbf{v}_i^T
$$



In [81]:
A = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9]])
U, S, VT = np.linalg.svd(A)

In [84]:
print("rank 1 approximation - S의 첫 번째 원소 x U의 첫 번째 열 x VT의 첫 번쨰 행")
Ahat1 = S[0] * np.outer(U[:, 0], VT[0, :])
Ahat1

rank 1 approximation - S의 첫 번째 원소 x U의 첫 번째 열 x VT의 첫 번쨰 행


array([[1.72611407, 2.07284981, 2.41958555],
       [3.36106599, 4.03622515, 4.7113843 ],
       [4.99601792, 5.99960048, 7.00318305],
       [6.63096985, 7.96297582, 9.2949818 ]])

In [90]:
print("rank 2 approximation - i=1,2일 때의 SUM")
Ahat2 = S[0] * np.outer(U[:,0], VT[0,:]) + S[1] * np.outer(U[:,1], VT[1,:])
print(Ahat2)
print("-> A의 rank가 2라 벌써 원본 값이 나옴")

rank 2 approximation - i=1,2일 때의 SUM
[[1. 2. 3.]
 [3. 4. 5.]
 [5. 6. 7.]
 [7. 8. 9.]]
-> A의 rank가 2라 벌써 원본 값이 나옴


In [88]:
print("rank 3 approximation - i=1,2,3일 떄의 SUM")
Ahat3 = S[0] * np.outer(U[:,0], VT[0,:]) + S[1] * np.outer(U[:,1], VT[1,:]) + S[2] * np.outer(U[:,2], VT[2,:])
Ahat3

rank 3 approximation - i=1,2,3일 떄의 SUM


array([[1., 2., 3.],
       [3., 4., 5.],
       [5., 6., 7.],
       [7., 8., 9.]])

In [92]:
print(S[2] * np.outer(U[:,2], VT[2,:]))
print("-> 거의 0")


array([[-1.66444394e-16,  3.32888787e-16, -1.66444394e-16],
       [ 9.10707641e-17, -1.82141528e-16,  9.10707641e-17],
       [ 3.17191652e-16, -6.34383305e-16,  3.17191652e-16],
       [-2.41818023e-16,  4.83636046e-16, -2.41818023e-16]])

In [96]:
#어떤 rank1 approximation이 가장 원본에 근접한지 Frobenius norm으로 확인하기
Ahat1 = S[0] * np.outer(U[:, 0], VT[0, :])
Ahat2 = S[1] * np.outer(U[:, 1], VT[1, :])
Ahat3 = S[2] * np.outer(U[:, 2], VT[2, :])

print(np.linalg.norm(A - Ahat1),",",np.linalg.norm(A - Ahat2),",",np.linalg.norm(A - Ahat3))
print("차가 적어 가장 값이 작은 Ahat1이 가장 원본에 근접한 rank 1 approximation")

1.1441171501608633 , 19.14917742219513 , 19.183326093250876
차가 적어 가장 값이 작은 Ahat1이 가장 원본에 근접한 rank 1 approximation
