<a href="https://colab.research.google.com/github/leejunho12316/HonGongMachine/blob/main/PyTorch_Tutorial/1_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

#Tensor의 기초

1. 데이터 -> tensor

In [3]:
#리스트 -> tensor
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

#numpy -> tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

<class 'torch.Tensor'>


In [6]:
#속성 유지하고 데이터 생성하기
x_ones = torch.ones_like(x_data) #shape
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float) #daratype, shape
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.8628, 0.8750],
        [0.5280, 0.6917]])


2. 무작위 tensor

In [14]:
#무작위 만들기
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[0.2308, 0.6311, 0.7353],
        [0.9518, 0.5763, 0.4406]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


3. tensor 접근

In [14]:
tensor = torch.rand(4,4)
print(tensor)
print(tensor[0,:])
print(tensor[:,0])
print(tensor[:, -1])
print(tensor[..., -1])

tensor([[0.4978, 0.7540, 0.9653, 0.5618],
        [0.7935, 0.9225, 0.1670, 0.5197],
        [0.3975, 0.3134, 0.0601, 0.6833],
        [0.6075, 0.5299, 0.3547, 0.7610]])
tensor([0.4978, 0.7540, 0.9653, 0.5618])
tensor([0.4978, 0.7935, 0.3975, 0.6075])
tensor([0.5618, 0.5197, 0.6833, 0.7610])
tensor([0.5618, 0.5197, 0.6833, 0.7610])


4. tensor 속성

In [19]:
tensor = torch.rand(3,4)
print(tensor.shape, tensor.dtype, tensor.device)

torch.Size([3, 4]) torch.float32 cpu


In [17]:
torch.cat([tensor, tensor, tensor], dim=1)

tensor([[0.4978, 0.7540, 0.9653, 0.5618, 0.4978, 0.7540, 0.9653, 0.5618, 0.4978,
         0.7540, 0.9653, 0.5618],
        [0.7935, 0.9225, 0.1670, 0.5197, 0.7935, 0.9225, 0.1670, 0.5197, 0.7935,
         0.9225, 0.1670, 0.5197],
        [0.3975, 0.3134, 0.0601, 0.6833, 0.3975, 0.3134, 0.0601, 0.6833, 0.3975,
         0.3134, 0.0601, 0.6833],
        [0.6075, 0.5299, 0.3547, 0.7610, 0.6075, 0.5299, 0.3547, 0.7610, 0.6075,
         0.5299, 0.3547, 0.7610]])

In [18]:
torch.stack([tensor,tensor,tensor])

tensor([[[0.4978, 0.7540, 0.9653, 0.5618],
         [0.7935, 0.9225, 0.1670, 0.5197],
         [0.3975, 0.3134, 0.0601, 0.6833],
         [0.6075, 0.5299, 0.3547, 0.7610]],

        [[0.4978, 0.7540, 0.9653, 0.5618],
         [0.7935, 0.9225, 0.1670, 0.5197],
         [0.3975, 0.3134, 0.0601, 0.6833],
         [0.6075, 0.5299, 0.3547, 0.7610]],

        [[0.4978, 0.7540, 0.9653, 0.5618],
         [0.7935, 0.9225, 0.1670, 0.5197],
         [0.3975, 0.3134, 0.0601, 0.6833],
         [0.6075, 0.5299, 0.3547, 0.7610]]])

5. 연산

In [42]:
y1 = tensor @ tensor.T #@ matmul : 행렬곱 T: 전치
tensor.matmul(tensor.T)


y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

tensor([[2.0637, 1.5437, 0.8761, 1.4719],
        [1.5437, 1.7786, 0.9697, 1.4257],
        [0.8761, 0.9697, 0.7268, 0.9489],
        [1.4719, 1.4257, 0.9489, 1.3549]])

In [46]:
tensor * tensor
tensor.mul(tensor)

tensor([[0.2478, 0.5685, 0.9319, 0.3156],
        [0.6296, 0.8510, 0.0279, 0.2701],
        [0.1580, 0.0982, 0.0036, 0.4669],
        [0.3691, 0.2808, 0.1258, 0.5791]])

In [48]:
tensor.sum().item()

8.889107704162598

#Numpy 변환

In [65]:
#tensor와 numpy배열은 메모리 공간을 공유하기 때문에 tensor 데이터 numpy 변환 가능. 단, tensor 변경시 numpy 데이터도 변함.
torch_data = torch.ones(5)
numpy_data = torch_data.numpy()
print(numpy_data)

torch_data.add_(1)
print(numpy_data)

[1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2.]


In [68]:
#numpy배열을 tensor로 변경했을 때도 마찬가지고 numpy변경시 tensorflow데이터도 변함.
n = np.ones(5)
t = torch.from_numpy(n)
print(n, t)

np.add(n, 1, out=n)
print(n, t)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
