<a href="https://colab.research.google.com/github/leejunho12316/HonGongMachine/blob/main/PyTorch_Tutorial/4_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EB%AA%A8%EB%8D%B8_%EA%B5%AC%EC%84%B1%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import os
import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms

device = 'cpu'

In [70]:
class NeuralNetwork(nn.Module):
  def __init__(self):
    super().__init__()
    self.flatten = nn.Flatten()
    self.linear_relu_stack = nn.Sequential(
        nn.Linear(28*28, 512),
        nn.ReLU(),
        nn.Linear(512, 512),
        nn.ReLU(),
        nn.Linear(512,10)
    )

  def forward(self, x):
    x = self.flatten(x)
    logits = self.linear_relu_stack(x)
    return logits

model = NeuralNetwork().to(device)
print(model)

X = torch.rand(1, 28, 28, device = device) #데이터
logits = model(X) #모델 통과
pred_probab = nn.Softmax(dim=1)(logits) #확률 출력
y_pred = pred_probab.argmax(1) #결과 출력

print('data : ', X[0][:2], ',,,,,,,,,,,,,,,,,,,,')
print('model result : ', logits)
print('Softmax : ', pred_probab)
print('result : ', y_pred)

NeuralNetwork(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu_stack): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
  )
)
data :  tensor([[6.7669e-01, 5.3524e-01, 7.2632e-01, 1.8539e-01, 6.5830e-01, 6.0686e-02,
         9.7370e-01, 3.6918e-01, 6.4150e-01, 4.2891e-01, 3.4752e-01, 6.2704e-01,
         6.0046e-01, 9.2330e-01, 3.1850e-01, 2.9897e-01, 7.6134e-01, 7.6343e-01,
         1.3391e-01, 9.3863e-01, 4.6269e-01, 6.2712e-01, 1.8047e-01, 2.9982e-01,
         8.6010e-01, 3.3189e-01, 1.6523e-02, 6.6694e-01],
        [9.4440e-01, 2.8234e-01, 2.2589e-01, 9.4891e-05, 4.0136e-01, 7.0084e-01,
         7.8442e-01, 4.9316e-01, 6.6832e-02, 8.3602e-01, 3.8443e-03, 9.0324e-01,
         6.0566e-01, 4.2896e-01, 5.0554e-01, 7.9907e-01, 1.1003e-01, 8.4374e-01,
         4.0604e-01, 3.0295e-01, 4.8034e-01, 3.8

In [88]:
rand_image = torch.rand(3,28,28)
print('original : ', rand_image.shape)

flatten = nn.Flatten()
flat_image = flatten(rand_image)
print('flattened : ', flat_image.shape)
print(flat_image)

print()

layer1 = nn.Linear(in_features = 28*28, out_features = 20)
hidden = layer1(flat_image)
print('hidden : ', hidden.shape)
print(hidden)

print()

relu = nn.ReLU()(hidden)
print('relu : ', relu.shape)
print(relu)

original :  torch.Size([3, 28, 28])
flattened :  torch.Size([3, 784])
tensor([[4.7274e-02, 2.9135e-01, 6.6789e-01,  ..., 5.9442e-01, 8.9608e-01,
         2.6283e-01],
        [3.0528e-01, 2.8304e-01, 6.8092e-04,  ..., 4.8130e-01, 6.4999e-01,
         8.8361e-01],
        [5.0646e-01, 9.8308e-01, 9.6842e-02,  ..., 2.5856e-01, 4.8427e-01,
         1.3436e-01]])

hidden :  torch.Size([3, 20])
tensor([[ 0.6182,  0.1057,  0.1355, -0.1398,  0.1548,  0.2561,  0.3264,  0.2698,
         -0.1744, -0.3323,  0.4931, -0.0262, -0.4919,  0.0608, -0.0236, -0.3155,
          0.0511,  0.2171,  0.1265, -0.2588],
        [ 0.8134,  0.2149, -0.1083, -0.4297,  0.0179,  0.5386,  0.5002,  0.0995,
         -0.0446, -0.3091,  0.5853,  0.1957, -0.1477, -0.2044,  0.0235, -0.2973,
          0.1677,  0.3870, -0.2596, -0.0863],
        [ 0.7105,  0.2701, -0.0671,  0.0041, -0.0177,  0.3582,  0.2376, -0.2780,
         -0.1964, -0.5570,  0.2263,  0.0853, -0.1784, -0.2683,  0.2177, -0.1844,
         -0.0562,  0.1598,  0

In [91]:
seq_modules = nn.Sequential(
    flatten,
    layer1,
    nn.ReLU(),
    nn.Linear(20,10)
)
input_image = torch.rand(3,28,28)
logits = seq_modules(input_image)
logits

tensor([[ 0.5331,  0.0834,  0.3622,  0.0660,  0.1898,  0.0381, -0.0850,  0.2935,
          0.1328,  0.1174],
        [ 0.2136,  0.2342,  0.0598,  0.0038,  0.2716,  0.1408, -0.1023,  0.1873,
         -0.0332, -0.0433],
        [ 0.2663,  0.2269,  0.0649,  0.0726,  0.2025,  0.2514,  0.0011,  0.2943,
          0.0555,  0.0077]], grad_fn=<AddmmBackward0>)

In [95]:
for name, param in model.named_parameters():
  print(name, param.size())

linear_relu_stack.0.weight torch.Size([512, 784])
linear_relu_stack.0.bias torch.Size([512])
linear_relu_stack.2.weight torch.Size([512, 512])
linear_relu_stack.2.bias torch.Size([512])
linear_relu_stack.4.weight torch.Size([10, 512])
linear_relu_stack.4.bias torch.Size([10])
